- hosts: localhost
  become: true
  become_user: root
  vars:
    default_users:
      - games
      - gopher
    groups_ad:
      - cisco
      - noaccess:
      - dba
    groups_rm:
      - users
      - games
      - dip
      - dip
      - cisco
  tasks:
    - name: create user accounts
      user:
        name: "{{ item }}"
        state: present
      with_items: 
        - " {{ default_users }}" 
