---
- hosts: localhost
  become: true
  become_user: root
 
  tasks:

    - name: Adding Multiple users
      user:
        name: "{{item }}"
        state: present
      with_items:
        - appuser
        - dbuser
        - appuat
